### ISSUE TITLE
Calibration and conversion of raw sensor values to real-world units

### ISSUE THREAD

**Issue by btroia** [haydnw/AirPi#17]
I was wondering if there were plans to update the calibration code to convert the readings to more human-readable units (ppm, dB, etc.) instead of the raw ohms or millivolts? Mainly for Nitrogen Dioxide, Carbon Monoxide, Volume, etc.?

I was happy to see some of the calibration formulas in /cfg/supports.cfg but they are all commented out and don't seem to convert units. Thanks!

**Comment by haydnw** [comment]
The nature of the sensors (primarily due to price point) means that they are inherently difficult to characterise. I am doing some work with a UK university at the moment to try and calibrate them against much more sensitive equipment (i.e. costing tens of thousands of pounds). There are two questions:

1) Is the sensor response the same for every sensor which comes out of the factory on to an AirPi board? For example, the resistance on a sensor might go up by a factor of 2 when a gas concentration increases by 10ppb, and the resistance on a different sensor (same model ) might go up by a factor of 2.2.

2) Do all of the sensors start with the same value? For example, if you put two sensors (same model) in pure nitrogen, do they both read the same base resistance?

This work is ongoing, but there is plenty of existing evidence to indicate that the reason the sensors are so cheap is that they aren't too consistent or easily characterised. There is plenty of literature out there; a Google search for TGS2600 (the optional VOC sensor), for example, gives plenty of papers looking at the potential usefulness and ability to calibrate that particular model.

So the short answer is: not at the moment. The final answer might even be: yes, but only if you calibrate your own sensors.

Obviously you can use the 'calibration' functions to adjust values if you do have a way of calibrating your particular sensors, but they are just too disparate in response for any generic calibration function to be applied to them all. Sorry!

Future discussion on this is probably best contained within the forum (http://airpi.freeforums.net/board/1/general-board), since it's not necessarily specific to my fork of the software.

Haydn
